#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

server:
  port: 5051

spring:
  application:
    name: ArticoliWebService
  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: admin
  password: admin123

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 3600 #secondi
    secret: $123_Stella@xantrix.it
    
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG
